/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Thrifty.Samples
{
  public enum ResultCode
  {
    OK = 0,
    TRY_LATER = 1,
  }
}
